### ISSUE TITLE
Error in building iOS (sorry for lack of details here)

### ISSUE THREAD

**Issue by jdvs1** [nordnet/cordova-universal-links-plugin#16]
cordova-universal-links-plugin 1.0.0 "Universal Links Plugin"

I don't mind giving more information at all. I'm not sure exactly what would help you in this situation. 

`cordova build` results in the following errors:

```
/Users/john/deeplink-app/platforms/ios/DeepLinkApp/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:57: error: expected '>'
@property (nonatomic, readonly, strong) NSArray<CULPath *> *paths;
                                                        ^
/Users/john/deeplink-app/platforms/ios/DeepLinkApp/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:58: error: expected member name or ';' after declaration specifiers
@property (nonatomic, readonly, strong) NSArray<CULPath *> *paths;
                                        ~~~~~~~          ^
/Users/john/deeplink-app/platforms/ios/DeepLinkApp/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:1: error: property requires fields to be named
@property (nonatomic, readonly, strong) NSArray<CULPath *> *paths;
^                                       ~~~~~~~~~~~~~~~~~
/Users/john/deeplink-app/platforms/ios/DeepLinkApp/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:58: error: expected ';' at end of declaration list
@property (nonatomic, readonly, strong) NSArray<CULPath *> *paths;
                                                         ^
                                                         ;
/Users/john/deeplink-app/platforms/ios/DeepLinkApp/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:58: error: expected identifier or '('
In file included from /Users/john/deeplink-app/platforms/ios/DeepLinkApp/Plugins/cordova-universal-links-plugin/CULPlugin.m:8:
/Users/john/deeplink-app/platforms/ios/DeepLinkApp/Plugins/cordova-universal-links-plugin/Parser/CULConfigXmlParser.h:20:20: error: expected '>'
+ (NSArray<CULHost *> *)parse;
                   ^
/Users/john/deeplink-app/platforms/ios/DeepLinkApp/Plugins/cordova-universal-links-plugin/Parser/CULConfigXmlParser.h:20:21: error: expected ')'
+ (NSArray<CULHost *> *)parse;
                    ^
/Users/john/deeplink-app/platforms/ios/DeepLinkApp/Plugins/cordova-universal-links-plugin/Parser/CULConfigXmlParser.h:20:3: note: to match this '('
+ (NSArray<CULHost *> *)parse;
  ^
7 errors generated.

** BUILD FAILED **


The following build commands failed:
  CompileC build/DeepLinkApp.build/Debug-iphonesimulator/DeepLinkApp.build/Objects-normal/i386/CULPlugin.o DeepLinkApp/Plugins/cordova-universal-links-plugin/CULPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/john/deeplink-app/platforms/ios/cordova/build-debug.xcconfig,-project,DeepLinkApp.xcodeproj,ARCHS=i386,-target,DeepLinkApp,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/john/deeplink-app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/john/deeplink-app/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/john/deeplink-app/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/john/deeplink-app/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/Users/john/.npm/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by jdvs1** [comment]
I'm using Xcode 6.4, and I see that Xcode 7+ is required. I'll try updating Xcode and see if that fixes the issue.
