### ISSUE TITLE
build failed on ios

### ISSUE THREAD

**Issue by roysG** [nordnet/cordova-universal-links-plugin#17]
..../www/picktags.com/public_html/app/platforms/ios/build/PickTags.build/Debug-iphonesimulator/PickTags.build/Objects-normal/i386/CULPlugin.o
In file included from /Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/CULPlugin.m:8:
In file included from /Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/Parser/CULConfigXmlParser.h:8:
/Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:57: error:
      expected '>'
@property (nonatomic, readonly, strong) NSArray<CULPath *> *paths;
                                                        ^
/Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:58: error:
      expected member name or ';' after declaration specifiers
@property (nonatomic, readonly, strong) NSArray<CULPath *> *paths;
                                        ~~~~~~~          ^
/Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:1: error:
      property requires fields to be named
@property (nonatomic, readonly, strong) NSArray<CULPath *> *paths;
^                                       ~~~~~~~~~~~~~~~~~
/Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:58: error:
      expected ';' at end of declaration list
@property (nonatomic, readonly, strong) NSArray<CULPath *> *paths;
                                                         ^
                                                         ;
/Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/Model/CULHost.h:36:58: error:
      expected identifier or '('
In file included from /Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/CULPlugin.m:8:
/Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/Parser/CULConfigXmlParser.h:20:20: error:
      expected '>'
- (NSArray<CULHost *> *)parse;
                 ^
  /Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/Parser/CULConfigXmlParser.h:20:21: error:
    expected ')'
- (NSArray<CULHost *> *)parse;
                  ^
  /Users/Admin/www/picktags.com/public_html/app/platforms/ios/PickTags/Plugins/cordova-universal-links-plugin/Parser/CULConfigXmlParser.h:20:3: note:
    to match this '('
- (NSArray<CULHost *> *)parse;
  ^
  7 errors generated.

*\* BUILD FAILED **

The following build commands failed:
    CompileC build/PickTags.build/Debug-iphonesimulator/PickTags.build/Objects-normal/i386/CULPlugin.o PickTags/Plugins/cordova-universal-links-plugin/CULPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Admin/www/picktags.com/public_html/app/platforms/ios/cordova/build-debug.xcconfig,-project,PickTags.xcodeproj,ARCHS=i386,-target,PickTags,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Admin/www/picktags.com/public_html/app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Admin/www/picktags.com/public_html/app/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/Admin/www/picktags.com/public_html/app/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/Admin/www/picktags.com/public_html/app/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

any ideas ?

cordova version: 5.3.3

platforms:
Installed platforms: android 4.1.1, ios 3.9.2
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, osx, webos

running on mac

**Comment by nikDemyankov** [comment]
My guess is that you are using older version of Xcode (probably 6). You need to update it to 7.

**Comment by roysG** [comment]
Thanks, i will update and let you know if it solved my problem.

**Comment by roysG** [comment]
nikDemyankov,
I try to install xcode 7 but to install it, apple force me to update to their new os.
The problem is that there are a lot of bad comment on new their new os.

Can you change the code that it will also work for comping xcode 6.4 as other plugins do ?
I also can manually make the change if it is not a big problem.

Many Thanks.

**Comment by nikDemyankov** [comment]
I can, but I like the new feature in Xcode 7 that allows you to define the type of objects that are stored in the array or a dictionary. Never liked that uncertainty in objective-c. 

But anyway, you will have to move to Xcode 7 eventually :)

**Comment by roysG** [comment]
If you make a fork for users that has version of xcode 6, we will say to you many many Thanks!

**Comment by nikDemyankov** [comment]
Closing it since there is a separate issue for Xcode 6 support.
