### ISSUE TITLE
Error after preparing for iOS: TypeError: v1.indexOf is not a function

### ISSUE THREAD

**Issue by johnborges** [nordnet/cordova-universal-links-plugin#71]
I'm getting an error after preparing the project for iOS. 

`Error: TypeError: v1.indexOf is not a function
    at compare (/CordovaProject/plugins/cordova-universal-links-plugin/node_modules/node-version-compare/index.js:3:20)
    at activateAssociativeDomains (/CordovaProject/plugins/cordova-universal-links-plugin/hooks/lib/ios/xcodePreferences.js:69:13)
    at Object.enableAssociativeDomainsCapability (/CordovaProject/plugins/cordova-universal-links-plugin/hooks/lib/ios/xcodePreferences.js:36:5)
    at activateUniversalLinksInIos (/CordovaProject/plugins/cordova-universal-links-plugin/hooks/afterPrepareHook.js:79:25)
    at /CordovaProject/plugins/cordova-universal-links-plugin/hooks/afterPrepareHook.js:50:11
    at Array.forEach (native)
    at run (/CordovaProject`

It looks like everything gets moved to the iOS project properly but I've found that I need to manually enable the "Associated Domain" toggle in my projects capabilities.

My setup:
cordova@6.2.0
cordova-ios@4.1.0

**Comment by nikDemyankov** [comment]
Weird... Try the following:
1. Remove plugin and iOS platform:
   
   ``` bash
   cordova plugin remove cordova-universal-links-plugin
   cordova platform remove ios
   ```
2. Add iOS platform and plugin:
   
   ``` bash
   cordova platform add ios
   cordova plugin add cordova-universal-links-plugin
   ```
3. Go to `YOUR_PROJECT_ROOT/plugins/cordova-universal-links-plugin/hooks/lib/ios/` and open `xcodePreferences.js`. In it comment out [lines 67-81](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/hooks/lib/ios/xcodePreferences.js#L67-L81).
4. Build again:
   
   ``` bash
   cordova build ios
   ```

**Comment by johnborges** [comment]
Worked. I got rid of [lines 67-76](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/hooks/lib/ios/xcodePreferences.js#L67-L76).

**Comment by martinlingstuyl** [comment]
I ran into this as well, added a pull request to fix this:
https://github.com/nordnet/cordova-universal-links-plugin/pull/154
